### ISSUE TITLE
errore cd .. dentro al labirinto

### ISSUE THREAD

**Issue by Rocco83** [esalvucci/Mayalinux#20]
dentro al labirinto, almeno con lxterminal, è possibile fare "cd .." fino ad una directory superiore alla radice del labirinto.

**Comment by esalvucci** [comment]
Risolto ma se uso cd ../../../../../ ecc... esco comunque dal labirinto, quindi lascio l'issue aperto.
Servirebbe qualcosa come chroot ma per chroot serve essere root

**Comment by ilmanzo** [comment]
potresti fare un alias del comando "cd" che prima di cambiare directory verifica se l'utente ha scritto qualche "/" , ad esempio

```
alias cd=mycd

mycd () 
{ 
    if [[ $1 != *"/"* ]]; then
        \cd $1
    fi
}

```

ovviamente poi negli script devi usare il comando \cd con backslash davanti altrimenti ti becchi sempre l'alias :)
